version: '3.9'
services:   
    php-apache-alumno: #App Alumno
      container_name: AppAlumno
      build: .
      restart: always
      ports:
        - 8080:80
      volumes:
        - ./AppAlumno:/var/www/html/AppAlumno
        - ./LogicaConexion:/var/www/html/LogicaConexion
        - ./index.php:/var/www/html/index.php
      networks:
        myq_network:
          aliases: 
            - myq_appalumno
      environment: 
        RAIZ: AppAlumno
      env_file:
        - webVariables.env
        
    php-apache-docente: #App Docente
      container_name: AppDocente
      build: .
      restart: always
      ports:
        - 8081:80
      volumes:
        - ./AppDocente:/var/www/html/AppDocente
        - ./LogicaConexion:/var/www/html/LogicaConexion
        - ./index.php:/var/www/html/index.php
      networks:
        myq_network:
          aliases: 
            - myq_appdocente
      environment: 
        RAIZ: AppDocente
      env_file:
        - webVariables.env

    php-apache-admin: #App Admin
      container_name: AppAdministrador
      build: .
      restart: always
      ports:
        - 8082:80
      volumes:
        - ./AppAdministrador/:/var/www/html/AppAdministrador
        - ./LogicaConexion/:/var/www/html/LogicaConexion
        - ./index.php:/var/www/html/index.php
      networks:
        myq_network:
          aliases: 
            - myq_appadmin
      environment:  
        RAIZ: AppAdministrador
      env_file:
        - webVariables.env
    
    mysql: #Base de Datos
      container_name: mysql
      image: mysql:5.7
      restart: always
      ports:
        - 3306:3306
      volumes:
        - mysql:/var/lib/mysql
      environment:
        MYSQL_DATABASE: database
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: root
      networks:
        myq_network:
          aliases: 
            - myq_database
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mysql:
networks:
  myq_network:
    name: myq_net
    driver: bridge
    ipam:
      driver: default